spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    driver-class-name: org.mariadb.jdbc.Driver
    username: developer
    password: password
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update